---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: i want to install java on ubuntu node
    apt:
      name: "{{myjavaonubuntu}}"
      state: present
    when: ansible_os_family=="Debian"
    
  - name: i want to install java on redhat node
    yum:
      name: "{{myjavaonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"