---
- hosts: 172.31.40.120
  become: yes
  tasks:
   - name: install git
     apt:
       namee: git
       state: present
     ignore_errors: yes   

   - name: install webserver
     apt:
       name: apache2
       state: present

   - name: install tree
     apt:
       name: tree
       state: present    
         